### ISSUE TITLE
Feature request - Experience to level deficit  

### ISSUE THREAD

**Issue by ghost** [SonicZentropy/PoE2Mods.pw#1]
A wonderful mod you have made and so quickly too - thank you for your work!

I'd like to suggest, even request an **addition** to your **multiclassing mod** - namely a '_experience to level_' deficit. Soloplay is a very big interest of mine, but experience gain is quite high in this game, with only 1 character, meaning you spend half the game being max level. 

**What I suggest** is that you keep the multiclassing restrictions removed, but make it possible to chose to either receive experience at a _slower rate_ (x0.75, x0.5...) or _require more experience_ to level (x1.25, x1.50...).

This could open up for a lot of **interesting multiclasses**, a myriad of **new skill combinations** and **prolong the game** for many players, while making sure multiclasses **still aren't overpowered**.

Thank you for reading my request.

**Comment by SonicZentropy** [comment]
That is a fantastic idea for solo.  I haven't traced any of the experience code yet, but this sounds like something totally doable

**Comment by SonicZentropy** [comment]
Found it, it's stored in JSON so you don't even need a mod to adjust it to your liking.  To find it, head to 

`Pillars of Eternity II\PillarsOfEternityII_Data\exported\design\gamedata`

now open global.gamedatabundle in whatever text editor you want.  You'll need a JSON formatter to make it readable -- I use Atom with PrettyJSON package.  Once you can read it, ctrl F for 

`"DebugName": "ExperienceTable",`

What follows is the exp values for every single level.  You can make them super huge if you want from there 👍

**Comment by ghost** [comment]
Absolutely fantastic, thank you sir!
Found the following in that file:
`PartySizeBonusExperiencePercent`

Putting it at _12_ results in a 25% deficit and putting it at _0_ results in a 50% deficit. The setting likely is only used when your party consists of 2 or fewer characters, so quite great for soloplay.

Again thank you!

**Comment by SonicZentropy** [comment]
Nice!  I'm going to move that into the Readme for other people looking for the same.  I'm sure there will be some.  Thanks for reporting back!
