### ISSUE TITLE
View encyclopedia of creature

### ISSUE THREAD

**Issue by brian-gates** [SonicZentropy/PoE2Mods.pw#3]
Is there any way to click or hover over a creature to view their encyclopedia?

Would love to help if you could point me in a direction. I'm new to this, but I love to learn!

**Comment by SonicZentropy** [comment]
You would have to build the UI for it yourself.  We have plans to work toward UI-based mods soon, but the process is much more involved than in PoE1, so I don't have any good direction to send you yet.  You can hop into our Discord server though, we're pretty active there working on stuff like this:

https://discord.gg/b3kJWYW
