### ISSUE TITLE
1.0.2 Patch Release

### ISSUE THREAD

**Issue by tjayharvey** [SonicZentropy/PoE2Mods.pw#4]
A new DLL was released with the patch today, needing a new release. Also, I was trying to create an Open Assembly out of Assembly-CSharp.dll myself and was finding that it was making public methods in the original assembly protected, breaking things in the existing mods. I assume there's something wrong with how I'm making the Open Assembly. Any help here?

**Comment by ExcerptNovela** [comment]
Just leaving a comment here to say I am experiencing the same thing. Viewing the resulting Open Assembly in decompiler shows protected flags on a lot of stuff, which I suspect is why I am being thrown protection errors.

Am I doing something wrong with using it from the command line? Can we get a specific set of instructions to ensure proper usage of that utility in this setting?

**Comment by SonicZentropy** [comment]
The new patch introduced something new that slightly bungled a lot of stuff.  The version of Open Assembly Creator in the new 2.0 release is fixed for the new patch though, enjoy!
