### ISSUE TITLE
Black Screen on Game Launch [v2.0]

### ISSUE THREAD

**Issue by LCzunko** [SonicZentropy/PoE2Mods.pw#7]
Running the game with an Assembly modified by the newest version of the modding framework (game version 1.02, framework version 2.0) results in a permanent black screen on launch. The game doesn't crash, it just stays at a black screen without even displaying the studio logos or changing the cursor. This seems to occur regardless of what 'ModIniFile.ini' settings are enabled. (Tried default config, everything disabled, and just difficulty indicators enabled.) The v1.20 release of the framework worked fine, so this is something newly introduced.

I'm willing to provide more info (logs?), just not sure what you need. Thanks for your work on this.

Oh, and I don't see AchievmentEnabler in the config file, is it just always on now?

**Comment by Nightliss** [comment]
Same issue here. Steam version.

**Comment by LCzunko** [comment]
Looked at the Discord, solved by putting 'INIFileParser.dll' in 'PillarsOfEternityII_Data\Managed'.

**Comment by Nightliss** [comment]
Yeah it worked. Thanks. Readme says it should go to the main folder where exe is located with .ini file.

**Comment by LCzunko** [comment]
New problem: can't load any of my saves. Getting a 'Loading Error' and the game puts me back in the main menu.

"There was an error loading the next map. Returned to Main Menu to prevent save game corruption."

Only mod enabled is DifficultyIconsMod - quest icons and character icons are on.

**Comment by Nightliss** [comment]
And I confirm. Hitting continue returns me to main menu with message above :/ Only MulticlassPenaltyRemover and DifficultyIcons enabled.

**Comment by fj** [comment]
Seconded! On Linux, running PoE 1.0.2.0089(1153) LAXE.

**Comment by fj** [comment]
@Aravane which Discord are you referring to?

**Comment by LCzunko** [comment]
@fj the one SonicZ mentioned in a reply to issue #3.

**Comment by SonicZentropy** [comment]
Ah yeah I have the wrong location for the INIFileParser, I'll go correct that in the Readme, thanks!

**Comment by SonicZentropy** [comment]
@Nightliss @Aravane can one of you send me a save file where you're having the issue?  I haven't gotten that yet, but I can surely take a look if I have a savegame

**Comment by LCzunko** [comment]
Sure. [Google Drive download.](https://drive.google.com/open?id=1KCGlYzupxLW2VrEivM82MkanpnE5uKLZ)

**Comment by SonicZentropy** [comment]
Should be fixed in 2.1!

**Comment by wandererhaha** [comment]
Same issue...

By the way, the launcher interface still display “1.0.1.64” and “patchwork version 0.9.1”?

**Comment by sneezepee** [comment]
Still getting black screen on launch with newest version.

**Comment by Epimetreus** [comment]
I can also confirm the problem Aravane was having with saved games not loading, even after the INIFileParser.dll is put in the proper location. I get a message about a failure to load the next map and returning to main menu to avoid corrupting the save file. [updated to correct the error message]
